# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b280a4f544c05903e07a7a10b7442955cc318394d1b519e8bf3fdccbc007359d41445962ee92c8d9f9bb6bd8b94cf0614e57f916ebeff415f8f2eb7f36a99c7

test:
  secret_key_base: b4f29e575acec8932a2d054b53570e4507abaf537ba0a673372b8d630d6bd192f343fdfd71281bd77ecb798f8198e01bd1a6c12313666aee74e358ef72e28597

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
